name: DockerCleaner
services:
  cleaner:
    build: .
    container_name: cleaner
    restart: unless-stopped
    volumes:
      # Mount Docker socket to allow container to manage other containers
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount logs directory to persist logs
      - ./logs:/app/logs
    environment:
      # Set timezone (adjust as needed)
      - TZ=UTC
    # Run with appropriate user permissions for Docker socket access
    user: "0:0"  # Run as root to access Docker socket
    networks:
      - cleaner_network

networks:
  cleaner_network:
    driver: bridge