[project]
name = "DockerCleaner"
version = "0.1.0"
description = "A scheduled Docker container manager to clean and restart containers"
requires-python = ">=3.13"
dependencies = [
    "schedule>=1.2.2",
]
